services:
  catalogdb:
    image: postgres:latest
    networks:
      - app-network
    
  basketdb:
    image: postgres:latest
    networks:
      - app-network
  distributedcache:
    image: redis
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile
    networks:
      - app-network

volumes:
  postgres_catalog:
  postgres_basket:

networks:
  app-network:
    driver: bridge
